#spring:
#  application:
#    name: gateway
#  cloud:
#    config:
#      enabled: false
#
#security:
#  basic:
#    enabled: true
#
#server:
#  port: 8080
#
#endpoints:
#  health:
#    sensitive: false
#
#management:
#  security:
#    enabled: false
