spring:
  application:
    name: gateway
  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
#        ip-address: 192.168.43.216
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
security:
  basic:
    enabled: true

server:
  port: 8080
endpoints:
  health:
    sensitive: false
